version: "3"

services:
  # Collector
  collector:
    env_file: ../.env
    image: otel/opentelemetry-collector-contrib:0.16.0
    command: ["--config=/conf/collector.yaml", "--log-level=DEBUG"]
    volumes:
      - ./collector.yaml:/conf/collector.yaml
    ports:
      - "9464:9464"
      - "55680:55680"
      - "55681:55681"